export const employeeActionsTypes = {
    SET_EMPLOYEE: 'SET_EMPLOYEE',
    ADD_CHECKED_EMPLOYEE: 'ADD_CHECKED_EMPLOYEE',
    REMOVE_CHECKED_EMPLOYEE: 'REMOVE_CHECKED_EMPLOYEE',
    CLEAR_EMPLOYEES: 'CLEAR_EMPLOYEES',
    SET_IS_ALL_CHECKED: 'SET_IS_ALL_CHECKED'
}
