export const companiesActionsTypes = {
    GET_COMPANIES: 'GET_COMPANIES',
    ADD_CHECKED_COMPANY: 'ADD_CHECKED_COMPANY',
    REMOVE_CHECKED_COMPANY: 'REMOVE_CHECKED_COMPANY',
    CLEAR_COMPANIES: 'CLEAR_COMPANIES',
    SET_IS_ALL_CHECKED: 'SET_IS_ALL_CHECKED'
}